### ISSUE TITLE
Test should run on the latest iOS version

### ISSUE THREAD

**Issue by Itaybre** [mercadolibre/fury_andesui-ios#84]
## Description 
Currently unit tests run on iOS [iOS11](https://github.com/mercadolibre/fury_andesui-ios/blob/develop/.circleci/config.yml#L61) and [iOS12](https://github.com/mercadolibre/fury_andesui-ios/blob/develop/.circleci/config.yml#L64)

### Setps to reproduce
1. Create a PR
2. Done

### Proof
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/860036/85761756-75e81280-b6e9-11ea-869d-23565f49d91b.png">

**Comment by tinchovictory** [comment]
Fixed on #125
